[package]
name = "voting"
version = "0.1.0"
authors = ["Topher Cawlfield <ccawlfield@gogoair.com>"]

[dependencies]
rand = "0.3"
lazy_static = "0.2"
ndarray = "0.9.0"
docopt = "0.8"
csv = "1.0.0-beta.5"
