[package]
name = "voting"
version = "0.1.0"
authors = ["Topher Cawlfield <ccawlfield@gogoair.com>"]
edition = '2021'

[dependencies]
rand = "0.8.5"
lazy_static = "1.4.0"
ndarray = "0.15.6"
docopt = "1.1.1"
csv = "1.0.0-beta.5"
rand_distr = "0.4.3"
clap = { version = "4.5.7", features = ["derive"] }
parquet = "52.0.0"
arrow-array = "52.0.0"
arrow-schema = "52.0.0"
meansd = "2.1.0"
