[package]
name = "voting"
version = "0.1.0"
authors = ["Topher Cawlfield <ccawlfield@gogoair.com>"]

[dependencies]
rand = "0.8.5"
lazy_static = "1.4.0"
ndarray = "0.15.6"
docopt = "1.1.1"
csv = "1.0.0-beta.5"
rand_distr = "0.4.3"
