voters = 101
candidates = 4

# Candidates can be drawn from a larger population using a multi-winner method
# primary_candidates = 7
[primary_method.RRV]
strat = "Honest"
ranks = 21
# 0.5 <= k <= 1.0 -- smaller values downweight appeased ballots more.
k = 0.5

[[considerations]]
Likability = { mean = 0.1 }
[[considerations]]
[[considerations.Issues.issues]]
# Analagous to left <-> right
sigma = 1.0
halfcsep = 2.0
halfvsep = 2.0
[[considerations.Issues.issues]]
# Analagous to libertarian <-> authoritarian
sigma = 0.5
halfcsep = 0.75
halfvsep = 0.75

[[methods]]
Plurality = { strat = "Honest" }

[[methods]]
Plurality = { strat = "Strategic" }

[[methods]]
[methods.Range]
strat = "Honest"
nranks = 10

[[methods]]
[methods.Range]
strat = "Strategic"
nranks = 10

[[methods]]  # Approval voting, honest
[methods.Range]
strat = "Honest"
nranks = 2

[[methods]]  # Approval voting, strategic
[methods.Range]
strat = "Strategic"
nranks = 2

[[methods]]  # IRV honest
[methods.InstantRunoff]

[[methods]]  # Borda honest
[methods.Borda]
