voters = 100
candidates = 4
likefactor = 0.4

[primary_method.RRV]
strat = "Honest"
ranks = 21
k = 0.5

[[methods]]
Plurality = { strat = "Honest" }

[[methods]]
Plurality = { strat = "Strategic" }

[[methods]]
[methods.Range]
strat = "Honest"
nranks = 10

[[methods]]
[methods.Range]
strat = "Strategic"
nranks = 10

[[methods]]  # Approval voting, honest
[methods.Range]
strat = "Honest"
nranks = 2

[[methods]]  # Approval voting, strategic
[methods.Range]
strat = "Strategic"
nranks = 2
